[package]
name = "godot_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.8"
godot = "0.2.4"
log = { version = "0.4.27", features = ["std"] }
